spring: 
  application: 
    name: eureka-server3
eureka:
  instance:
    hostname: 192.168.0.15
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:8763/eureka/, http://${eureka.instance.hostname}:8764/eureka/
server:
  enable-self-preservation: true